### ISSUE TITLE
Device initialization has failed

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-update-tool#4]
Update Tool 0.4, Windows 10.
![screenshot](https://user-images.githubusercontent.com/1450547/41317537-c4da1bd4-6e95-11e8-8f58-0845dd446207.png)

**Comment by szszszsz** [comment]
Hi! Was it run with Administrator privileges?
I will try to reproduce it on my side in a moment.

**Comment by jans23** [comment]
Yes, executed as Administrator.
-- 
Sent from a mobile device.

**Comment by szszszsz** [comment]
I have not reproduced it on Windows 10 Pro (up-to-date) with build from latest commit. Please retest on next release. I will add more debug messages for `code 1` case.

**Comment by szszszsz** [comment]
Please retest with https://github.com/Nitrokey/nitrokey-update-tool/releases/tag/v0.5-rc1

**Comment by jans23** [comment]
I retested (as Administrator) and the same issue appeared. Is there any
way to collect more debug information? 

Also I noticed that there is still no warning when starting the tool as
non-Administrator.

**Comment by szszszsz** [comment]
Please use the build from 
https://github.com/Nitrokey/nitrokey-update-tool/releases/tag/v0.5-rc1-debug
and attach `dfu-programmer.log` file, which should be created in the same directory as application.

**Comment by szszszsz** [comment]
Provided log shows:
```
/app/3rdparty/dfu-programmer/src/dfu.c:402: Could not open found device, libusb_open error code: -12
```
which might point to not installed drivers in the OS. However, Update Tool (concretely, the drivers installer) has not reported any issues during their installation.

**Comment by szszszsz** [comment]
Confirmed it works on a fresh Windows 10 VM in two separate reproduction attempts.
It started to work after reinstalling the driver with the `Zadig` utility. 
Closing for now, as no reproduction environment is available. Will be reopened, if would not work further.
