### ISSUE TITLE
Misleading message after successful flashing

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-update-tool#6]
After successful updating the firmware the tool identifies the flashed device and displays the following message: "Nitrokey Storage detected in Production mode. Please enable Firmware Update mode in Nitrokey App first (Configure -> Enable Firmware Update)."

However, in this case the user usually doesn't want to flash again so the message is misleading. Ideally the message shouldn't be displayed after successful flashing. However the message makes sense when starting the tool (prior to flashing). Could this be changed accordingly?

**Comment by szszszsz** [comment]
OK! The message will not be shown after the first successful flashing.

**Comment by szszszsz** [comment]
After the successful flashing only the one message will be shown: `Nitrokey Storage detected in Update mode`, and only, if the device will be connected again in Update mode during the same Tool's run.
